### ISSUE TITLE
[Fix] Detail 뷰에서 UI 수정사항 반영

### ISSUE THREAD

**Issue by i-colours-u** [Health-Food-Me/Health-Food-Me-iOS#121]
## 🛠 Issue
Detail 뷰에서 있는 수정사항 및 버그를 수정합니다.

## 📝 To-do

- [ ] 전화번호 터치영역 확인하기
- [ ] 외식대처법 탭이 스크롤 시작시에 색상이 변ㄹ하도록 처리하기
- [ ] 리뷰쓰기 버튼이 리뷰 탭에서만 나타나도록 처리하기
