### ISSUE TITLE
[Fix] 리뷰 리스트 조회 API 수정 사항 및 QA 반영

### ISSUE THREAD

**Issue by yungu0010** [Health-Food-Me/Health-Food-Me-iOS#135]
## 🛠 Issue

- API 수정 사항에 맞춰 코드 수정
- QA 반영

## 📝 To-do

- [x] 리뷰 리스트 조회 API 수정 사항 반영
- [x] 햄버거바 행간 조정
- [x]  수정사항 제보 오타 수정
