### ISSUE TITLE
[Fix] 검색 디테일 수정

### ISSUE THREAD

**Issue by 0inn** [Health-Food-Me/Health-Food-Me-iOS#138]
## 🛠 Issue

- 검색 및 스크랩 UI 수정합니다

## 📝 To-do

- [x] 목록보기 기능 추가
- [x] 지도보기 레이아웃 수정
- [x] 검색 리스트 별점 크기
- [x] km / m 변경
- [x] 검색리스트로 플로우 변경
- [x] 텍스트 필드 공백 제거
