### ISSUE TITLE
[Fix] 메인 및 설정 UI 수정 작업

### ISSUE THREAD

**Issue by i-colours-u** [Health-Food-Me/Health-Food-Me-iOS#139]
## 🛠 Issue
기타 뷰에서 부족하거나, 오류가 있는 UI 부분을 수정합니다.

## 📝 To-do

- [x] 메인맵에서 돋보기 이미지 추가
- [x] 설정뷰에서 신고하기 추가
- [x] 햄버거바 전환 애니메이션 체크하기
- [x] 다른 이벤트 클릭시 메인맵 click event 해제하기
