### ISSUE TITLE
[Fix] 검색 플로우 오류 수정 & 메인 지도 줌 스케일 설정 & 위치 권한 없을 시 분기처리

### ISSUE THREAD

**Issue by L-j-h-c** [Health-Food-Me/Health-Food-Me-iOS#205]
## 🛠 Issue

검색 플로우 오류 수정 & 메인 지도 줌 스케일 설정 & 유저 플로우 설정

## 📝 To-do

- [ ] 검색 플로우 오류 수정
- [x] 메인 지도 줌 스케일 설정
- [ ] 위치 권한 없을 시 분기처리
