### ISSUE TITLE
[Fix] 리젝 사유 관련 수정사항

### ISSUE THREAD

**Issue by L-j-h-c** [Health-Food-Me/Health-Food-Me-iOS#210]
## 📝 To-do

- [x] 애플 로그인 문구 수정
- [x] 애플 지도 URLScheme 추가
- [x] 자동 로그인 구현
