### ISSUE TITLE
[Feat] 음식 검색 기능 구현

### ISSUE THREAD

**Issue by 0inn** [Health-Food-Me/Health-Food-Me-iOS#266]
## 🛠 Issue

음식 검색 구현합니다.

## 📝 To-do

- [x] 식당 자동검색
- [x] 식당 검색 결과 조회
- [x] 음식 검색 UI 구현
- [x] 카테고리 검색 API 연동
- [x] 최근검색어 구현
