### ISSUE TITLE
[Fix] 음식 검색 관련 수정사항 반영

### ISSUE THREAD

**Issue by 0inn** [Health-Food-Me/Health-Food-Me-iOS#279]
## 🛠 Issue

음식 검색 관련 이슈 수정합니다.

## 📝 To-do

- [x] 최근검색어 삭제 안되는 이슈 수정
- [x] 카테고리 검색 시 타이틀 고정
- [x] 식당 검색 시 첫번째 카테고리 타이틀
