### ISSUE TITLE
[fix] 외식대처법 UI 디테일 수정

### ISSUE THREAD

**Issue by i-colours-u** [Health-Food-Me/Health-Food-Me-iOS#289]
## 🛠 Issue

외식대처법 UI 디테일 수정하기

## 📝 To-do

- [ ] 외식대처법에서 카테고리 1개일 때, 박스 밖으로 벗어나는 경우 UI 수정
- [ ] 추천하는 이유 <--> 이렇게 드셔보세요 라인 간격 늘리기
- [ ] 박스 margin 20으로 줄이기
- [ ] 컨텐츠 영역이 넘칠 때, 홈버튼 영역 간격 조절하기
