### ISSUE TITLE
[Fix] 요약 보기 및 상세 페이지 디테일 수정

### ISSUE THREAD

**Issue by L-j-h-c** [Health-Food-Me/Health-Food-Me-iOS#295]
## 🛠 Issue

요약 보기 및 상세 페이지 디테일 수정

## 📝 To-do

- [x] 요약보기 태그 디자인 수정
- [x] 요약보기 별 사이즈 수정
- [x] 상세 페이지 위치 아이콘 크기 수정
- [x] 상세 페이지 별 사이즈 수정
