### ISSUE TITLE
[Fix] Height 짧은 기종(ex iPhone 12mini)에서 외식대처법 짤리는 이슈 수정 + 블로그 토글 사라지는 이슈

### ISSUE THREAD

**Issue by i-colours-u** [Health-Food-Me/Health-Food-Me-iOS#315]
## 🛠 Issue
Height 짧은 기종(ex iPhone 12mini)에서 외식대처법 짤리는 이슈 수정

## 📝 To-do

- [x] 외식대처법 box height 계산식 검토
- [x] 외식대처법 마지막 줄과 간격 56px 맞추기
- [x] 외식대처법 컨텐츠 textView Leading/trailing 검토
- [ ] 블로그 토글 사라지는 이슈 처리
