### ISSUE TITLE
[Feat] 검색 관련 로직 정리

### ISSUE THREAD

**Issue by 0inn** [Health-Food-Me/Health-Food-Me-iOS#53]
## 🛠 Issue

- 최근 검색어 / 자동 완성어 / 검색 완성 / 검색 실패 플로우 정리합니다.
- Realm 관련 디테일 수정합니다.
- 나머지 디테일들 전부 구현합니다....

## 📝 To-do

- [x] 최근 검색어 - 자동 완성어 - 검색 완성
- [x] 검색 완성 - 검색 실패 X 버튼 로직 처리
- [x] StarView 구현
- [x] cellSelected 이벤트 추가
- [x] Realm 중복 체크
- [x] 검색 실패 시, Realm 저장 X
- [x] 데이터 모델 추가
- [x] 자동 완성어 특정 라벨 색 변경
