### ISSUE TITLE
[Fix] Map Detail - 스크롤 액션 처리 수정

### ISSUE THREAD

**Issue by i-colours-u** [Health-Food-Me/Health-Food-Me-iOS#75]
## 🛠 Issue
메인 맵 부분에서 스크롤 액션을 처리합니다.
<img width="410" alt="스크린샷 2022-07-15 오후 1 40 01" src="https://user-images.githubusercontent.com/60260284/179151870-b6528529-b439-4ef8-bfd4-71b900cba4cd.png">

## 📝 To-do
- [ ] 아래 컨텐츠를 내렸을때, 전체 내려가도록 처리
- [ ] 아래 컨텐츠를 조금이라도 올렸을때, 아래 컨텐츠는 고정된 채로 올리기
- [ ] 영업 시간 부분을 확장한 이후에 스크롤 액션 수정하기
